import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: {
    absolute: "", // fixed text agar dekhana hai to ye show hoga
    default: "Next JS Learning Tutorial", // Default ye show hoga title
    template: "%s | CodeEvoluation", // jis page me title defifne kiya hoga waha ye append hoga suffix
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="winter">
      <body suppressHydrationWarning={true} className={inter.className}>
        <header className="flex p-6 bg-slate-500 items-center justify-center">
          <p className=" font-bold text-white">Google Docx API</p>
        </header>
        <div className="h-screen">{children}</div>
        {/* <footer className="flex p-6  bg-red-400 items-center justify-center">
          <p>FOOTER</p>
        </footer> */}
      </body>
    </html>
  );
}
